from __future__ import annotations


class DynamicUint:
    def __init__(self, value: int | DynamicUint = 0) -> None: ...

    def __add__(self, other: DynamicUint) -> DynamicUint: ...
    def __sub__(self, other: DynamicUint) -> DynamicUint: ...
    def __or__(self, other: int) -> DynamicUint: ...
    def __and__(self, other: int) -> DynamicUint: ...
    def __lshift__(self, shift: int) -> DynamicUint: ...
    def __rshift__(self, shift: int) -> DynamicUint: ...

    def __iadd__(self, other: DynamicUint) -> DynamicUint: ...
    def __isub__(self, other: DynamicUint) -> DynamicUint: ...
    def __ior__(self, other: int) -> DynamicUint: ...
    def __iand__(self, other: int) -> DynamicUint: ...
    def __ilshift__(self, shift: int) -> DynamicUint: ...
    def __irshift__(self, shift: int) -> DynamicUint: ...

    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __lt__(self, other: DynamicUint) -> bool: ...
    def __le__(self, other: DynamicUint) -> bool: ...
    def __gt__(self, other: DynamicUint) -> bool: ...
    def __ge__(self, other: DynamicUint) -> bool: ...

    def __bool__(self) -> bool: ...

    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

    def to_binary(self) -> str: ...
    def shift_grow(self, shift: int) -> DynamicUint: ...
    def get_empty(self) -> DynamicUint: ...
